# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    async def ChooseActionForm1(self, agent_position: types.Position,goal_position: types.Position,water_tiles: types.Positions,grid_size: int,
        baml_options: BamlCallOptions = {},
    ) -> types.DMM_Output:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="ChooseActionForm1", args={
            "agent_position": agent_position,"goal_position": goal_position,"water_tiles": water_tiles,"grid_size": grid_size,
        })
        return typing.cast(types.DMM_Output, result.cast_to(types, types, stream_types, False, __runtime__))
    async def ChooseActionForm2(self, agent_position: types.Position,goal_position: types.Position,water_tiles: types.Positions,grid_size: int,hint: str,
        baml_options: BamlCallOptions = {},
    ) -> types.DMM_Output:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="ChooseActionForm2", args={
            "agent_position": agent_position,"goal_position": goal_position,"water_tiles": water_tiles,"grid_size": grid_size,"hint": hint,
        })
        return typing.cast(types.DMM_Output, result.cast_to(types, types, stream_types, False, __runtime__))
    async def ChooseActionForm3(self, agent_position: types.Position,goal_position: types.Position,water_tiles: types.Positions,grid_size: int,
        baml_options: BamlCallOptions = {},
    ) -> types.DMM_Output:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="ChooseActionForm3", args={
            "agent_position": agent_position,"goal_position": goal_position,"water_tiles": water_tiles,"grid_size": grid_size,
        })
        return typing.cast(types.DMM_Output, result.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractAction(self, coordinates: typing.List[int],goal_position: typing.List[int],water_tiles: typing.List[int],
        baml_options: BamlCallOptions = {},
    ) -> types.DMM_Output:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractAction", args={
            "coordinates": coordinates,"goal_position": goal_position,"water_tiles": water_tiles,
        })
        return typing.cast(types.DMM_Output, result.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractActionGoalInformation(self, coordinates: typing.List[int],goal_position: typing.List[int],water_tiles: typing.List[int],
        baml_options: BamlCallOptions = {},
    ) -> types.DMM_Output:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractActionGoalInformation", args={
            "coordinates": coordinates,"goal_position": goal_position,"water_tiles": water_tiles,
        })
        return typing.cast(types.DMM_Output, result.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractCoordinates(self, coordinates: typing.List[int],
        baml_options: BamlCallOptions = {},
    ) -> types.Test_Coordinates:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractCoordinates", args={
            "coordinates": coordinates,
        })
        return typing.cast(types.Test_Coordinates, result.cast_to(types, types, stream_types, False, __runtime__))
    async def MacroActionExecution(self, agent_position: types.Position,target_position: types.Position,obligations: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.NavigationAgent", "types.PullOutOfWater"]:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="MacroActionExecution", args={
            "agent_position": agent_position,"target_position": target_position,"obligations": obligations,
        })
        return typing.cast(typing.Union["types.NavigationAgent", "types.PullOutOfWater"], result.cast_to(types, types, stream_types, False, __runtime__))
    async def TestWaterTiles(self, agent_position: types.Position,water_tiles: types.Positions,goal_position: types.Position,
        baml_options: BamlCallOptions = {},
    ) -> types.Position:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="TestWaterTiles", args={
            "agent_position": agent_position,"water_tiles": water_tiles,"goal_position": goal_position,
        })
        return typing.cast(types.Position, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ChooseActionForm1(self, agent_position: types.Position,goal_position: types.Position,water_tiles: types.Positions,grid_size: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.DMM_Output, types.DMM_Output]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="ChooseActionForm1", args={
            "agent_position": agent_position,"goal_position": goal_position,"water_tiles": water_tiles,"grid_size": grid_size,
        })
        return baml_py.BamlStream[stream_types.DMM_Output, types.DMM_Output](
          result,
          lambda x: typing.cast(stream_types.DMM_Output, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.DMM_Output, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ChooseActionForm2(self, agent_position: types.Position,goal_position: types.Position,water_tiles: types.Positions,grid_size: int,hint: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.DMM_Output, types.DMM_Output]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="ChooseActionForm2", args={
            "agent_position": agent_position,"goal_position": goal_position,"water_tiles": water_tiles,"grid_size": grid_size,"hint": hint,
        })
        return baml_py.BamlStream[stream_types.DMM_Output, types.DMM_Output](
          result,
          lambda x: typing.cast(stream_types.DMM_Output, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.DMM_Output, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ChooseActionForm3(self, agent_position: types.Position,goal_position: types.Position,water_tiles: types.Positions,grid_size: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.DMM_Output, types.DMM_Output]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="ChooseActionForm3", args={
            "agent_position": agent_position,"goal_position": goal_position,"water_tiles": water_tiles,"grid_size": grid_size,
        })
        return baml_py.BamlStream[stream_types.DMM_Output, types.DMM_Output](
          result,
          lambda x: typing.cast(stream_types.DMM_Output, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.DMM_Output, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractAction(self, coordinates: typing.List[int],goal_position: typing.List[int],water_tiles: typing.List[int],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.DMM_Output, types.DMM_Output]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractAction", args={
            "coordinates": coordinates,"goal_position": goal_position,"water_tiles": water_tiles,
        })
        return baml_py.BamlStream[stream_types.DMM_Output, types.DMM_Output](
          result,
          lambda x: typing.cast(stream_types.DMM_Output, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.DMM_Output, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractActionGoalInformation(self, coordinates: typing.List[int],goal_position: typing.List[int],water_tiles: typing.List[int],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.DMM_Output, types.DMM_Output]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractActionGoalInformation", args={
            "coordinates": coordinates,"goal_position": goal_position,"water_tiles": water_tiles,
        })
        return baml_py.BamlStream[stream_types.DMM_Output, types.DMM_Output](
          result,
          lambda x: typing.cast(stream_types.DMM_Output, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.DMM_Output, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractCoordinates(self, coordinates: typing.List[int],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.Test_Coordinates, types.Test_Coordinates]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractCoordinates", args={
            "coordinates": coordinates,
        })
        return baml_py.BamlStream[stream_types.Test_Coordinates, types.Test_Coordinates](
          result,
          lambda x: typing.cast(stream_types.Test_Coordinates, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Test_Coordinates, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def MacroActionExecution(self, agent_position: types.Position,target_position: types.Position,obligations: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.Union["stream_types.NavigationAgent", "stream_types.PullOutOfWater"], typing.Union["types.NavigationAgent", "types.PullOutOfWater"]]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="MacroActionExecution", args={
            "agent_position": agent_position,"target_position": target_position,"obligations": obligations,
        })
        return baml_py.BamlStream[typing.Union["stream_types.NavigationAgent", "stream_types.PullOutOfWater"], typing.Union["types.NavigationAgent", "types.PullOutOfWater"]](
          result,
          lambda x: typing.cast(typing.Union["stream_types.NavigationAgent", "stream_types.PullOutOfWater"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Union["types.NavigationAgent", "types.PullOutOfWater"], x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def TestWaterTiles(self, agent_position: types.Position,water_tiles: types.Positions,goal_position: types.Position,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.Position, types.Position]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="TestWaterTiles", args={
            "agent_position": agent_position,"water_tiles": water_tiles,"goal_position": goal_position,
        })
        return baml_py.BamlStream[stream_types.Position, types.Position](
          result,
          lambda x: typing.cast(stream_types.Position, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Position, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ChooseActionForm1(self, agent_position: types.Position,goal_position: types.Position,water_tiles: types.Positions,grid_size: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ChooseActionForm1", args={
            "agent_position": agent_position,"goal_position": goal_position,"water_tiles": water_tiles,"grid_size": grid_size,
        }, mode="request")
        return result
    async def ChooseActionForm2(self, agent_position: types.Position,goal_position: types.Position,water_tiles: types.Positions,grid_size: int,hint: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ChooseActionForm2", args={
            "agent_position": agent_position,"goal_position": goal_position,"water_tiles": water_tiles,"grid_size": grid_size,"hint": hint,
        }, mode="request")
        return result
    async def ChooseActionForm3(self, agent_position: types.Position,goal_position: types.Position,water_tiles: types.Positions,grid_size: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ChooseActionForm3", args={
            "agent_position": agent_position,"goal_position": goal_position,"water_tiles": water_tiles,"grid_size": grid_size,
        }, mode="request")
        return result
    async def ExtractAction(self, coordinates: typing.List[int],goal_position: typing.List[int],water_tiles: typing.List[int],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractAction", args={
            "coordinates": coordinates,"goal_position": goal_position,"water_tiles": water_tiles,
        }, mode="request")
        return result
    async def ExtractActionGoalInformation(self, coordinates: typing.List[int],goal_position: typing.List[int],water_tiles: typing.List[int],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractActionGoalInformation", args={
            "coordinates": coordinates,"goal_position": goal_position,"water_tiles": water_tiles,
        }, mode="request")
        return result
    async def ExtractCoordinates(self, coordinates: typing.List[int],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractCoordinates", args={
            "coordinates": coordinates,
        }, mode="request")
        return result
    async def MacroActionExecution(self, agent_position: types.Position,target_position: types.Position,obligations: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="MacroActionExecution", args={
            "agent_position": agent_position,"target_position": target_position,"obligations": obligations,
        }, mode="request")
        return result
    async def TestWaterTiles(self, agent_position: types.Position,water_tiles: types.Positions,goal_position: types.Position,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="TestWaterTiles", args={
            "agent_position": agent_position,"water_tiles": water_tiles,"goal_position": goal_position,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ChooseActionForm1(self, agent_position: types.Position,goal_position: types.Position,water_tiles: types.Positions,grid_size: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ChooseActionForm1", args={
            "agent_position": agent_position,"goal_position": goal_position,"water_tiles": water_tiles,"grid_size": grid_size,
        }, mode="stream")
        return result
    async def ChooseActionForm2(self, agent_position: types.Position,goal_position: types.Position,water_tiles: types.Positions,grid_size: int,hint: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ChooseActionForm2", args={
            "agent_position": agent_position,"goal_position": goal_position,"water_tiles": water_tiles,"grid_size": grid_size,"hint": hint,
        }, mode="stream")
        return result
    async def ChooseActionForm3(self, agent_position: types.Position,goal_position: types.Position,water_tiles: types.Positions,grid_size: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ChooseActionForm3", args={
            "agent_position": agent_position,"goal_position": goal_position,"water_tiles": water_tiles,"grid_size": grid_size,
        }, mode="stream")
        return result
    async def ExtractAction(self, coordinates: typing.List[int],goal_position: typing.List[int],water_tiles: typing.List[int],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractAction", args={
            "coordinates": coordinates,"goal_position": goal_position,"water_tiles": water_tiles,
        }, mode="stream")
        return result
    async def ExtractActionGoalInformation(self, coordinates: typing.List[int],goal_position: typing.List[int],water_tiles: typing.List[int],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractActionGoalInformation", args={
            "coordinates": coordinates,"goal_position": goal_position,"water_tiles": water_tiles,
        }, mode="stream")
        return result
    async def ExtractCoordinates(self, coordinates: typing.List[int],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractCoordinates", args={
            "coordinates": coordinates,
        }, mode="stream")
        return result
    async def MacroActionExecution(self, agent_position: types.Position,target_position: types.Position,obligations: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="MacroActionExecution", args={
            "agent_position": agent_position,"target_position": target_position,"obligations": obligations,
        }, mode="stream")
        return result
    async def TestWaterTiles(self, agent_position: types.Position,water_tiles: types.Positions,goal_position: types.Position,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="TestWaterTiles", args={
            "agent_position": agent_position,"water_tiles": water_tiles,"goal_position": goal_position,
        }, mode="stream")
        return result
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))