# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ChooseActionForm1(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DMM_Output:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChooseActionForm1", llm_response=llm_response, mode="request")
        return typing.cast(types.DMM_Output, result)

    def ChooseActionForm2(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DMM_Output:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChooseActionForm2", llm_response=llm_response, mode="request")
        return typing.cast(types.DMM_Output, result)

    def ChooseActionForm3(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DMM_Output:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChooseActionForm3", llm_response=llm_response, mode="request")
        return typing.cast(types.DMM_Output, result)

    def ExtractAction(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DMM_Output:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractAction", llm_response=llm_response, mode="request")
        return typing.cast(types.DMM_Output, result)

    def ExtractActionGoalInformation(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DMM_Output:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractActionGoalInformation", llm_response=llm_response, mode="request")
        return typing.cast(types.DMM_Output, result)

    def ExtractCoordinates(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Test_Coordinates:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractCoordinates", llm_response=llm_response, mode="request")
        return typing.cast(types.Test_Coordinates, result)

    def MacroActionExecution(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.NavigationAgent", "types.PullOutOfWater"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="MacroActionExecution", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.NavigationAgent", "types.PullOutOfWater"], result)

    def TestWaterTiles(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Position:
        result = self.__options.merge_options(baml_options).parse_response(function_name="TestWaterTiles", llm_response=llm_response, mode="request")
        return typing.cast(types.Position, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ChooseActionForm1(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.DMM_Output:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChooseActionForm1", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.DMM_Output, result)

    def ChooseActionForm2(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.DMM_Output:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChooseActionForm2", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.DMM_Output, result)

    def ChooseActionForm3(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.DMM_Output:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChooseActionForm3", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.DMM_Output, result)

    def ExtractAction(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.DMM_Output:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractAction", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.DMM_Output, result)

    def ExtractActionGoalInformation(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.DMM_Output:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractActionGoalInformation", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.DMM_Output, result)

    def ExtractCoordinates(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Test_Coordinates:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractCoordinates", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Test_Coordinates, result)

    def MacroActionExecution(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.NavigationAgent", "stream_types.PullOutOfWater"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="MacroActionExecution", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.NavigationAgent", "stream_types.PullOutOfWater"], result)

    def TestWaterTiles(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Position:
        result = self.__options.merge_options(baml_options).parse_response(function_name="TestWaterTiles", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Position, result)

    