# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ChooseActionV1(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DMM_Output:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChooseActionV1", llm_response=llm_response, mode="request")
        return typing.cast(types.DMM_Output, result)

    def ChooseActionV2(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DMM_Output:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChooseActionV2", llm_response=llm_response, mode="request")
        return typing.cast(types.DMM_Output, result)

    def ExtractAction(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DMM_Output:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractAction", llm_response=llm_response, mode="request")
        return typing.cast(types.DMM_Output, result)

    def ExtractActionGoalInformation(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DMM_Output:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractActionGoalInformation", llm_response=llm_response, mode="request")
        return typing.cast(types.DMM_Output, result)

    def ExtractCoordinates(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Test_Coordinates:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractCoordinates", llm_response=llm_response, mode="request")
        return typing.cast(types.Test_Coordinates, result)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="request")
        return typing.cast(types.Resume, result)

    def TestWaterTiles(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Position:
        result = self.__options.merge_options(baml_options).parse_response(function_name="TestWaterTiles", llm_response=llm_response, mode="request")
        return typing.cast(types.Position, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ChooseActionV1(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.DMM_Output:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChooseActionV1", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.DMM_Output, result)

    def ChooseActionV2(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.DMM_Output:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChooseActionV2", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.DMM_Output, result)

    def ExtractAction(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.DMM_Output:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractAction", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.DMM_Output, result)

    def ExtractActionGoalInformation(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.DMM_Output:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractActionGoalInformation", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.DMM_Output, result)

    def ExtractCoordinates(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Test_Coordinates:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractCoordinates", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Test_Coordinates, result)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Resume:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Resume, result)

    def TestWaterTiles(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Position:
        result = self.__options.merge_options(baml_options).parse_response(function_name="TestWaterTiles", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Position, result)

    