# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (9)
# #########################################################################

class DMM_Output(BaseModel):
    position: typing.List[int]
    reasoning: typing.Optional[str] = None

class NavigationAgent(BaseModel):
    tool_name: typing.Optional[str] = None
    goal_position_coordinates: typing.List[int]

class Obligation(BaseModel):
    obligation: typing.Optional[str] = None

class Position(BaseModel):
    row: typing.Optional[int] = None
    column: typing.Optional[int] = None

class Positions(BaseModel):
    positions: typing.List["Position"]

class PullOutOfWater(BaseModel):
    tool_name: typing.Optional[str] = None
    description_of_the_action: typing.Optional[str] = None

class SpotNextToPerson(BaseModel):
    tool_name: typing.Optional[str] = None
    goal_position_coordinates: typing.List[int]

class State(BaseModel):
    agent_position: typing.Optional["Position"] = None
    person_positions: typing.Optional["Positions"] = None

class Test_Coordinates(BaseModel):
    x: typing.Optional[int] = None
    y: typing.Optional[int] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
