# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.DMM_Output": types.DMM_Output,
    "stream_types.DMM_Output": stream_types.DMM_Output,

    "types.Position": types.Position,
    "stream_types.Position": stream_types.Position,

    "types.Positions": types.Positions,
    "stream_types.Positions": stream_types.Positions,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.State": types.State,
    "stream_types.State": stream_types.State,

    "types.Test_Coordinates": types.Test_Coordinates,
    "stream_types.Test_Coordinates": stream_types.Test_Coordinates,


}