# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.DMM_Output": types.DMM_Output,
    "stream_types.DMM_Output": stream_types.DMM_Output,

    "types.NavigationAgent": types.NavigationAgent,
    "stream_types.NavigationAgent": stream_types.NavigationAgent,

    "types.Obligation": types.Obligation,
    "stream_types.Obligation": stream_types.Obligation,

    "types.Position": types.Position,
    "stream_types.Position": stream_types.Position,

    "types.Positions": types.Positions,
    "stream_types.Positions": stream_types.Positions,

    "types.PullOutOfWater": types.PullOutOfWater,
    "stream_types.PullOutOfWater": stream_types.PullOutOfWater,

    "types.SpotNextToPerson": types.SpotNextToPerson,
    "stream_types.SpotNextToPerson": stream_types.SpotNextToPerson,

    "types.State": types.State,
    "stream_types.State": stream_types.State,

    "types.Test_Coordinates": types.Test_Coordinates,
    "stream_types.Test_Coordinates": stream_types.Test_Coordinates,


}